# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojj2n5cK6bjMhTIiAktTRiwQF7cGF3kj
"""

import math
expansion=float(input("mm a expandir"))
activacion=0.133
relacion=expansion/activacion
print("activar",relacion)

